### ISSUE TITLE
Issues compiling vmtrace on MacOS

### ISSUE THREAD

**Issue by metonymic-smokey** [odnoklassniki/jvmti-tools#1]
The `jni_md.h` file is stored in the `include/darwin` directory in MacOS. `jni.h` references it resulting in a compilation error. To fix this, either the  location of `jni_md.h` has to be changed to `include` or `jni.h` should be changed.

Adding a small note in README for Mac users would clear this out.

**Comment by apangin** [comment]
The standard JNI headers should never be changed or moved.
The right way is to set the proper include path with `-I` compiler option.

README provides an example compilation command for Linux. It doesn't mention a command for macOS. It is quite similar, except that the path `-I $JAVA_HOME/include/linux` should be obviously changed to `-I $JAVA_HOME/include/darwin`.
